
export const tasks = [
  // Для проекта "Разработка приложения для аутстаффинга" (id = 1)
  // Колонка "Разработка концепции" (id = 1)
  {
    title: "Разработка технического задания",
    description: "Определение требований",
    execution_priority: 1,
    executorId: 1,
    columnId: 1,
    projectId: 1,
    status: 1,
    dead_line: new Date("2025-11-15"),
    creator: 1,
  },
  {
    title: "Создание прототипа",
    description: "Разработка базового прототипа",
    execution_priority: 2,
    executorId: 2,
    columnId: 1,
    projectId: 1,
    status: 1,
    dead_line: new Date("2025-11-20"),
    creator: 2,
  },

  // Колонка "Верстка и дизайн" (id = 2)
  {
    title: "Дизайн интерфейса",
    description: "Создание дизайна UI",
    execution_priority: 1,
    executorId: 1,
    columnId: 2,
    projectId: 1,
    status: 1,
    dead_line: new Date("2025-11-25"),
    creator: 1,
  },
  {
    title: "Верстка страниц",
    description: "Создание HTML/CSS",
    execution_priority: 2,
    executorId: 2,
    columnId: 2,
    projectId: 1,
    status: 1,
    dead_line: new Date("2025-11-30"),
    creator: 2,
  },
  {
    title: "Адаптивная верстка",
    description: "Сделать сайт адаптивным",
    execution_priority: 3,
    executorId: 1,
    columnId: 2,
    projectId: 1,
    status: 1,
    dead_line: new Date("2025-12-05"),
    creator: 1,
  },

  // Колонка "Тестирование" (id = 3)
  {
    title: "Юнит-тестирование",
    description: "Писать юнит-тесты",
    execution_priority: 1,
    executorId: 2,
    columnId: 3,
    projectId: 1,
    status: 1,
    dead_line: new Date("2025-12-10"),
    creator: 2,
  },
  {
    title: "Интеграционное тестирование",
    description: "Проверка интеграции",
    execution_priority: 2,
    executorId: 1,
    columnId: 3,
    projectId: 1,
    status: 1,
    dead_line: new Date("2025-12-15"),
    creator: 1,
  },

  // Колонка "Развертывание" (id = 4)
  {
    title: "Настройка сервера",
    description: "Настройка сервера для развертывания",
    execution_priority: 1,
    executorId: 2,
    columnId: 4,
    projectId: 1,
    status: 1,
    dead_line: new Date("2025-12-20"),
    creator: 2,
  },
  {
    title: "Развертывание приложения",
    description: "Развернуть приложение на сервере",
    execution_priority: 2,
    executorId: 1,
    columnId: 4,
    projectId: 1,
    status: 1,
    dead_line: new Date("2025-12-25"),
    creator: 1,
  },
  {
    title: "Настройка CI/CD",
    description: "Настройка пайплайнов",
    execution_priority: 3,
    executorId: 2,
    columnId: 4,
    projectId: 1,
    status: 1,
    dead_line: new Date("2025-12-30"),
    creator: 2
  },
  {
    title: "Мониторинг производительности",
    description: "Отслеживать производительность",
    execution_priority: 1,
    executorId: 1,
    columnId: 4,
    projectId: 1,
    status: 1,
    dead_line: new Date("2026-01-05"),
    creator: 1,
  },

  // Для проекта "Практика ОНИКС 2023" (id = 2)
  // Колонка "Разработка технического задания" (id = 5)
  {
    title: "Определение требований",
    description: "Определить требования заказчика",
    execution_priority: 1,
    executorId: 1,
    columnId: 5,
    projectId: 2,
    status: 1,
    dead_line: new Date("2025-10-15"),
    creator: 2,
  },
  {
    title: "Создание технического задания",
    description: "Написать техническое задание",
    execution_priority: 2,
    executorId: 2,
    columnId: 5,
    projectId: 2,
    status: 1,
    dead_line: new Date("2025-10-20"),
    creator: 1,
  },

  // Колонка "Создание прототипа" (id = 6)
  {
    title: "Разработка базового прототипа",
    description: "Создать базовый прототип",
    execution_priority: 1,
    executorId: 1,
    columnId: 6,
    projectId: 2,
    status: 1,
    dead_line: new Date("2025-10-25"),
    creator: 2,
  },
  {
    title: "Тестирование прототипа",
    description: "Проверить прототип",
    execution_priority: 2,
    executorId: 2,
    columnId: 6,
    projectId: 2,
    status: 1,
    dead_line: new Date("2025-10-30"),
    creator: 1,
  },

  // Колонка "Тестирование и отладка" (id = 7)
  {
    title: "Юнит-тестирование",
    description: "Писать юнит-тесты",
    execution_priority: 1,
    executorId: 2,
    columnId: 7,
    projectId: 2,
    status: 1,
    dead_line: new Date("2025-11-05"),
    creator: 2,
  },
  {
    title: "Интеграционное тестирование",
    description: "Проверка интеграции",
    execution_priority: 2,
    executorId: 1,
    columnId: 7,
    projectId: 2,
    status: 1,
    dead_line: new Date("2025-11-10"),
    creator: 1,
  },
  {
    title: "Отладка ошибок",
    description: "Исправить ошибки",
    execution_priority: 3,
    executorId: 2,
    columnId: 7,
    projectId: 2,
    status: 1,
    dead_line: new Date("2025-11-15"),
    creator: 2,
  },

  // Для проекта "Проект из архива" (id = 3)
  // Колонка "Анализ требований" (id = 8)
  {
    title: "Сбор требований",
    description: "Собрать требования",
    execution_priority: 1,
    executorId: 1,
    columnId: 8,
    projectId: 3,
    status: 1,
    dead_line: new Date("2025-09-15"),
    creator: 1,
  },
  {
    title: "Анализ требований",
    description: "Проанализировать требования",
    execution_priority: 2,
    executorId: 2,
    columnId: 8,
    projectId: 3,
    status: 1,
    dead_line: new Date("2025-09-20"),
    creator: 2,
  },

  // Колонка "Разработка архитектуры" (id = 9)
  {
    title: "Разработка архитектуры",
    description: "Создать архитектуру",
    execution_priority: 1,
    executorId: 1,
    columnId: 9,
    projectId: 3,
    status: 1,
    dead_line: new Date("2025-09-25"),
    creator: 1,
  },
  {
    title: "Планирование этапов",
    description: "Спланировать этапы разработки",
    execution_priority: 2,
    executorId: 2,
    columnId: 9,
    projectId: 3,
    status: 1,
    dead_line: new Date("2025-09-30"),
    creator: 2,
  },
  {
    title: "Создание прототипа",
    description: "Создать базовый прототип",
    execution_priority: 3,
    executorId: 1,
    columnId: 9,
    projectId: 3,
    status: 1,
    dead_line: new Date("2025-10-05"),
    creator: 1,
  },

  // Для проекта "Создание сайта для стартапа" (id = 4)
  // Колонка "Дизайн и верстка" (id = 10)
  {
    title: "Дизайн интерфейса",
    description: "Создать дизайн UI",
    execution_priority: 1,
    executorId: 1,
    columnId: 10,
    projectId: 4,
    status: 1,
    dead_line: new Date("2025-08-15"),
    creator: 2,
  },
  {
    title: "Верстка страниц",
    description: "Создать HTML/CSS",
    execution_priority: 2,
    executorId: 2,
    columnId: 10,
    projectId: 4,
    status: 1,
    dead_line: new Date("2025-08-20"),
    creator: 1,
  },
  {
    title: "Адаптивная верстка",
    description: "Сделать сайт адаптивным",
    execution_priority: 3,
    executorId: 1,
    columnId: 10,
    projectId: 4,
    status: 1,
    dead_line: new Date("2025-08-25"),
    creator: 2,
  },
  {
    title: "Тестирование верстки",
    description: "Проверить верстку",
    execution_priority: 1,
    executorId: 2,
    columnId: 10,
    projectId: 4,
    status: 1,
    dead_line: new Date("2025-08-30"),
    creator: 1,
  },

  // Колонка "Разработка функционала" (id = 11)
  {
    title: "Разработка функционала",
    description: "Создать функционал",
    execution_priority: 1,
    executorId: 1,
    columnId: 11,
    projectId: 4,
    status: 0,
    dead_line: new Date("2025-09-05"),
    creator: 2,
  },
  {
    title: "Тестирование функционала",
    description: "Проверить функционал",
    execution_priority: 2,
    executorId: 2,
    columnId: 11,
    projectId: 4,
    status: 1,
    dead_line: new Date("2025-09-10"),
    creator: 1,
  },
  {
    title: "Оптимизация кода",
    description: "Оптимизировать код",
    execution_priority: 3,
    executorId: 1,
    columnId: 11,
    projectId: 4,
    status: 1,
    dead_line: new Date("2025-09-15"),
    creator: 2,
  },

  // Колонка "Тестирование и запуск" (id = 12)
  {
    title: "Юнит-тестирование",
    description: "Писать юнит-тесты",
    execution_priority: 1,
    executorId: 2,
    columnId: 12,
    projectId: 4,
    status: 1,
    dead_line: new Date("2025-09-20"),
    creator: 1,
  },
  {
    title: "Интеграционное тестирование",
    description: "Проверка интеграции",
    execution_priority: 2,
    executorId: 1,
    columnId: 12,
    projectId: 4,
    status: 1,
    dead_line: new Date("2025-09-25"),
    creator: 2,
  },

  // Колонка "Мониторинг и поддержка" (id = 13)
  {
    title: "Настройка мониторинга",
    description: "Настроить мониторинг",
    execution_priority: 1,
    executorId: 2,
    columnId: 13,
    projectId: 4,
    status: 1,
    dead_line: new Date("2025-09-30"),
    creator: 1,
  },
  {
    title: "Поддержка и обновления",
    description: "Проводить обновления",
    execution_priority: 2,
    executorId: 1,
    columnId: 13,
    projectId: 4,
    status: 1,
    dead_line: new Date("2025-10-05"),
    creator: 2,
  },
  {
    title: "Анализ производительности",
    description: "Отслеживать производительность",
    execution_priority: 3,
    executorId: 2,
    columnId: 13,
    projectId: 4,
    status: 1,
    dead_line: new Date("2025-10-10"),
    creator: 1,
  },

  // Для проекта "Разработка CRM-системы" (id = 5)
  // Колонка "Анализ бизнес-требований" (id = 14)
  {
    title: "Сбор бизнес-требований",
    description: "Собрать бизнес-требования",
    execution_priority: 1,
    executorId: 1,
    columnId: 14,
    projectId: 5,
    status: 1,
    dead_line: new Date("2025-07-15"),
    creator: 2,
  },
  {
    title: "Анализ требований",
    description: "Проанализировать требования",
    execution_priority: 2,
    executorId: 2,
    columnId: 14,
    projectId: 5,
    status: 1,
    dead_line: new Date("2025-07-20"),
    creator: 1,
  },

  // Колонка "Разработка базы данных" (id = 15)
  {
    title: "Разработка базы данных",
    description: "Создать базу данных",
    execution_priority: 1,
    executorId: 1,
    columnId: 15,
    projectId: 5,
    status: 1,
    dead_line: new Date("2025-07-25"),
    creator: 2,
  },
  {
    title: "Настройка БД",
    description: "Настроить базу данных",
    execution_priority: 2,
    executorId: 2,
    columnId: 15,
    projectId: 5,
    status: 1,
    dead_line: new Date("2025-07-30"),
    creator: 1,
  },
  {
    title: "Тестирование БД",
    description: "Проверить базу данных",
    execution_priority: 3,
    executorId: 1,
    columnId: 15,
    projectId: 5,
    status: 1,
    dead_line: new Date("2025-08-05"),
    creator: 2,
  },

  // Колонка "Разработка интерфейса" (id = 16)
  {
    title: "Дизайн интерфейса",
    description: "Создать дизайн UI",
    execution_priority: 1,
    executorId: 2,
    columnId: 16,
    projectId: 5,
    status: 1,
    dead_line: new Date("2025-08-10"),
    creator: 1,
  },
  {
    title: "Верстка страниц",
    description: "Создать HTML/CSS",
    execution_priority: 2,
    executorId: 1,
    columnId: 16,
    projectId: 5,
    status: 1,
    dead_line: new Date("2025-08-15"),
    creator: 2,
  },
];
